"""Initiation, create User and Token tables.

Revision ID: f0820f91cba9
Revises: 
Create Date: 2017-07-25 13:16:03.922425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0820f91cba9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=40), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('expiredOn', sa.DateTime(), nullable=True),
    sa.Column('objectCode', sa.SmallInteger(), nullable=False),
    sa.Column('objectId', sa.Integer(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emailAddress', sa.String(length=255), nullable=False),
    sa.Column('displayName', sa.String(length=255), nullable=False),
    sa.Column('passwordHashed', sa.String(length=255), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=False),
    sa.Column('updatedOn', sa.DateTime(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_emailAddress'), 'user', ['emailAddress'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_emailAddress'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
